apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: development
  name: editor-binding
subjects:
  - kind: User
    name: platform-engineer
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: k8s-editor
  apiGroup: rbac.authorization.k8s.io
