apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development
  name: k8s-viewer
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments", "configmaps", "nodes"]
    verbs: ["get", "list", "watch"]
